#pragma once

#include"Camera.hpp"
#include"Color.hpp"
#include"Constants.hpp"
#include"Geometry.hpp"
#include"Keyboard.hpp"
#include"Matrix.hpp"
#include"Vectors.hpp"
#include"Rects.hpp"
#include"Script.hpp"
#include"Vectors.hpp"
#include"WindowManager.hpp"
#include"X3D.hpp"
#include"x3dMath.hpp"